// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// allChildrenCPP
std::vector<std::vector<int>> allChildrenCPP(const arma::Mat<int> E);
RcppExport SEXP _mitodrift_allChildrenCPP(SEXP ESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<int> >::type E(ESEXP);
    rcpp_result_gen = Rcpp::wrap(allChildrenCPP(E));
    return rcpp_result_gen;
END_RCPP
}
// reorder_rows
arma::Mat<int> reorder_rows(arma::Mat<int> x, arma::Col<int> y);
RcppExport SEXP _mitodrift_reorder_rows(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::Col<int> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(reorder_rows(x, y));
    return rcpp_result_gen;
END_RCPP
}
// reorderRcpp
arma::Mat<int> reorderRcpp(arma::Mat<int> E);
RcppExport SEXP _mitodrift_reorderRcpp(SEXP ESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<int> >::type E(ESEXP);
    rcpp_result_gen = Rcpp::wrap(reorderRcpp(E));
    return rcpp_result_gen;
END_RCPP
}
// nnin_cpp
std::vector<arma::Mat<int>> nnin_cpp(const arma::Mat<int> E, const int n);
RcppExport SEXP _mitodrift_nnin_cpp(SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Mat<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nnin_cpp(E, n));
    return rcpp_result_gen;
END_RCPP
}
// node_depth
NumericVector node_depth(int ntip, NumericVector e1, NumericVector e2, int nedge, NumericVector xx, int method);
RcppExport SEXP _mitodrift_node_depth(SEXP ntipSEXP, SEXP e1SEXP, SEXP e2SEXP, SEXP nedgeSEXP, SEXP xxSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< int >::type nedge(nedgeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(node_depth(ntip, e1, e2, nedge, xx, method));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp
double logSumExp(const arma::vec& x);
RcppExport SEXP _mitodrift_logSumExp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp(x));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp
double score_tree_bp(arma::Mat<int> E, const arma::mat& logP, const arma::mat& logA);
RcppExport SEXP _mitodrift_score_tree_bp(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_wrapper
arma::vec score_tree_bp_wrapper(arma::Mat<int> E, const arma::cube& logP, const arma::mat& logA);
RcppExport SEXP _mitodrift_score_tree_bp_wrapper(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_wrapper(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// logSumExpMat
arma::vec logSumExpMat(const arma::mat& X, int axis);
RcppExport SEXP _mitodrift_logSumExpMat(SEXP XSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExpMat(X, axis));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_multi
arma::vec score_tree_bp_multi(arma::Mat<int> E, const arma::cube& logP, const arma::cube& logA);
RcppExport SEXP _mitodrift_score_tree_bp_multi(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Mat<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_multi(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// nni_cpp_parallel
NumericVector nni_cpp_parallel(const List tree, const arma::cube& logP, const arma::mat& logA);
RcppExport SEXP _mitodrift_nni_cpp_parallel(SEXP treeSEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(nni_cpp_parallel(tree, logP, logA));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mitodrift_allChildrenCPP", (DL_FUNC) &_mitodrift_allChildrenCPP, 1},
    {"_mitodrift_reorder_rows", (DL_FUNC) &_mitodrift_reorder_rows, 2},
    {"_mitodrift_reorderRcpp", (DL_FUNC) &_mitodrift_reorderRcpp, 1},
    {"_mitodrift_nnin_cpp", (DL_FUNC) &_mitodrift_nnin_cpp, 2},
    {"_mitodrift_node_depth", (DL_FUNC) &_mitodrift_node_depth, 6},
    {"_mitodrift_logSumExp", (DL_FUNC) &_mitodrift_logSumExp, 1},
    {"_mitodrift_score_tree_bp", (DL_FUNC) &_mitodrift_score_tree_bp, 3},
    {"_mitodrift_score_tree_bp_wrapper", (DL_FUNC) &_mitodrift_score_tree_bp_wrapper, 3},
    {"_mitodrift_logSumExpMat", (DL_FUNC) &_mitodrift_logSumExpMat, 2},
    {"_mitodrift_score_tree_bp_multi", (DL_FUNC) &_mitodrift_score_tree_bp_multi, 3},
    {"_mitodrift_nni_cpp_parallel", (DL_FUNC) &_mitodrift_nni_cpp_parallel, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mitodrift(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
