// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// prop_clades_par
Rcpp::NumericVector prop_clades_par(Rcpp::IntegerMatrix E_target, SEXP edges, bool rooted, bool normalize);
RcppExport SEXP _mitodrift_prop_clades_par(SEXP E_targetSEXP, SEXP edgesSEXP, SEXP rootedSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type E_target(E_targetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< bool >::type rooted(rootedSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(prop_clades_par(E_target, edges, rooted, normalize));
    return rcpp_result_gen;
END_RCPP
}
// prop_clades_par_bm_se
Rcpp::List prop_clades_par_bm_se(Rcpp::IntegerMatrix E_target, SEXP edges, int nbatch, bool rooted);
RcppExport SEXP _mitodrift_prop_clades_par_bm_se(SEXP E_targetSEXP, SEXP edgesSEXP, SEXP nbatchSEXP, SEXP rootedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type E_target(E_targetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type nbatch(nbatchSEXP);
    Rcpp::traits::input_parameter< bool >::type rooted(rootedSEXP);
    rcpp_result_gen = Rcpp::wrap(prop_clades_par_bm_se(E_target, edges, nbatch, rooted));
    return rcpp_result_gen;
END_RCPP
}
// compute_node_edge_stats_bp2
Rcpp::List compute_node_edge_stats_bp2(arma::Col<int> E, const std::vector< std::vector<double> >& logP_list, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_compute_node_edge_stats_bp2(SEXP ESEXP, SEXP logP_listSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP_list(logP_listSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(compute_node_edge_stats_bp2(E, logP_list, logA));
    return rcpp_result_gen;
END_RCPP
}
// get_leaf_liks_mat_cpp
List get_leaf_liks_mat_cpp(const IntegerMatrix& amat, const IntegerMatrix& dmat, const NumericVector& vafs, double eps, int ncores, bool log);
RcppExport SEXP _mitodrift_get_leaf_liks_mat_cpp(SEXP amatSEXP, SEXP dmatSEXP, SEXP vafsSEXP, SEXP epsSEXP, SEXP ncoresSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type amat(amatSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dmat(dmatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vafs(vafsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(get_leaf_liks_mat_cpp(amat, dmat, vafs, eps, ncores, log));
    return rcpp_result_gen;
END_RCPP
}
// reorderRcpp
arma::Col<int> reorderRcpp(const arma::Col<int>& E);
RcppExport SEXP _mitodrift_reorderRcpp(SEXP ESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    rcpp_result_gen = Rcpp::wrap(reorderRcpp(E));
    return rcpp_result_gen;
END_RCPP
}
// nnin_cpp
std::vector<arma::Col<int>> nnin_cpp(const arma::Col<int>& E, const int n);
RcppExport SEXP _mitodrift_nnin_cpp(SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nnin_cpp(E, n));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp
double logSumExp(const arma::vec& x);
RcppExport SEXP _mitodrift_logSumExp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp(x));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp
double score_tree_bp(const arma::Col<int>& E, const std::vector<double>& logP, const std::vector<double>& logA, const int n, const int C, const int m, const int root);
RcppExport SEXP _mitodrift_score_tree_bp(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP nSEXP, SEXP CSEXP, SEXP mSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp(E, logP, logA, n, C, m, root));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_wrapper
double score_tree_bp_wrapper(arma::Col<int> E, const std::vector< std::vector<double> >& logP_list, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_score_tree_bp_wrapper(SEXP ESEXP, SEXP logP_listSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP_list(logP_listSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_wrapper(E, logP_list, logA));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp2
double score_tree_bp2(const arma::Col<int>& E, const std::vector<double>& logP, const std::vector<double>& logA, const int n, const int C, const int m, const int root);
RcppExport SEXP _mitodrift_score_tree_bp2(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP nSEXP, SEXP CSEXP, SEXP mSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp2(E, logP, logA, n, C, m, root));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_wrapper2
double score_tree_bp_wrapper2(arma::Col<int> E, const std::vector< std::vector<double> >& logP_list, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_score_tree_bp_wrapper2(SEXP ESEXP, SEXP logP_listSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP_list(logP_listSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_wrapper2(E, logP_list, logA));
    return rcpp_result_gen;
END_RCPP
}
// score_trees_parallel
NumericVector score_trees_parallel(const std::vector<arma::Col<int>>& trees, const std::vector< std::vector<double> >& logP, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_score_trees_parallel(SEXP treesSEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<arma::Col<int>>& >::type trees(treesSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_trees_parallel(trees, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_wrapper_multi
double score_tree_bp_wrapper_multi(arma::Col<int> E, const std::vector< std::vector<double> >& logP_list, const std::vector< std::vector<double> >& logA_list);
RcppExport SEXP _mitodrift_score_tree_bp_wrapper_multi(SEXP ESEXP, SEXP logP_listSEXP, SEXP logA_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP_list(logP_listSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logA_list(logA_listSEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_wrapper_multi(E, logP_list, logA_list));
    return rcpp_result_gen;
END_RCPP
}
// nni_cpp_parallel
NumericVector nni_cpp_parallel(arma::Col<int> E, const std::vector<std::vector<double>> logP, const std::vector<double> logA);
RcppExport SEXP _mitodrift_nni_cpp_parallel(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>> >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(nni_cpp_parallel(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// nni_cpp_parallel_cached
NumericVector nni_cpp_parallel_cached(arma::Col<int> E, const std::vector<std::vector<double>>& logP, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_nni_cpp_parallel_cached(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(nni_cpp_parallel_cached(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// nni_cpp_parallel_multi
NumericVector nni_cpp_parallel_multi(arma::Col<int> E, const std::vector<std::vector<double>> logP, const std::vector<std::vector<double>> logA);
RcppExport SEXP _mitodrift_nni_cpp_parallel_multi(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>> >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>> >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(nni_cpp_parallel_multi(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// tree_mcmc_cpp
std::vector<arma::Col<int>> tree_mcmc_cpp(arma::Col<int> E, const std::vector< std::vector<double> >& logP, const std::vector<double>& logA, int max_iter, int seed);
RcppExport SEXP _mitodrift_tree_mcmc_cpp(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP max_iterSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_mcmc_cpp(E, logP, logA, max_iter, seed));
    return rcpp_result_gen;
END_RCPP
}
// tree_mcmc_cpp_cached
std::vector<arma::Col<int>> tree_mcmc_cpp_cached(arma::Col<int> E, const std::vector< std::vector<double> >& logP, const std::vector<double>& logA, int max_iter, int seed);
RcppExport SEXP _mitodrift_tree_mcmc_cpp_cached(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP max_iterSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_mcmc_cpp_cached(E, logP, logA, max_iter, seed));
    return rcpp_result_gen;
END_RCPP
}
// tree_mcmc_cpp_cached_threadsafe
std::vector<arma::Col<int>> tree_mcmc_cpp_cached_threadsafe(arma::Col<int> E, const std::vector< std::vector<double> >& logP, const std::vector<double>& logA, int max_iter, int seed, bool reorder);
RcppExport SEXP _mitodrift_tree_mcmc_cpp_cached_threadsafe(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP max_iterSEXP, SEXP seedSEXP, SEXP reorderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type reorder(reorderSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_mcmc_cpp_cached_threadsafe(E, logP, logA, max_iter, seed, reorder));
    return rcpp_result_gen;
END_RCPP
}
// tree_mcmc_parallel
std::vector< std::vector<arma::Col<int>> > tree_mcmc_parallel(arma::Col<int> E, const std::vector< std::vector<double> >& logP, const std::vector<double>& logA, int max_iter, int nchains);
RcppExport SEXP _mitodrift_tree_mcmc_parallel(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP max_iterSEXP, SEXP nchainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type nchains(nchainsSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_mcmc_parallel(E, logP, logA, max_iter, nchains));
    return rcpp_result_gen;
END_RCPP
}
// tree_mcmc_parallel_seeded
std::vector< std::vector<arma::Col<int>> > tree_mcmc_parallel_seeded(std::vector< arma::Col<int> > start_edges, const std::vector< std::vector<double> >& logP, const std::vector<double>& logA, const std::vector<int>& max_iter_vec, const std::vector<int>& seeds);
RcppExport SEXP _mitodrift_tree_mcmc_parallel_seeded(SEXP start_edgesSEXP, SEXP logPSEXP, SEXP logASEXP, SEXP max_iter_vecSEXP, SEXP seedsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector< arma::Col<int> > >::type start_edges(start_edgesSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type max_iter_vec(max_iter_vecSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type seeds(seedsSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_mcmc_parallel_seeded(start_edges, logP, logA, max_iter_vec, seeds));
    return rcpp_result_gen;
END_RCPP
}
// save_qd_cpp
SEXP save_qd_cpp(const Rcpp::List& objects, const Rcpp::CharacterVector& paths, int compress_level, bool shuffle, std::size_t grain_size);
RcppExport SEXP _mitodrift_save_qd_cpp(SEXP objectsSEXP, SEXP pathsSEXP, SEXP compress_levelSEXP, SEXP shuffleSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type objects(objectsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< int >::type compress_level(compress_levelSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle(shuffleSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type grain_size(grain_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(save_qd_cpp(objects, paths, compress_level, shuffle, grain_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mitodrift_prop_clades_par", (DL_FUNC) &_mitodrift_prop_clades_par, 4},
    {"_mitodrift_prop_clades_par_bm_se", (DL_FUNC) &_mitodrift_prop_clades_par_bm_se, 4},
    {"_mitodrift_compute_node_edge_stats_bp2", (DL_FUNC) &_mitodrift_compute_node_edge_stats_bp2, 3},
    {"_mitodrift_get_leaf_liks_mat_cpp", (DL_FUNC) &_mitodrift_get_leaf_liks_mat_cpp, 6},
    {"_mitodrift_reorderRcpp", (DL_FUNC) &_mitodrift_reorderRcpp, 1},
    {"_mitodrift_nnin_cpp", (DL_FUNC) &_mitodrift_nnin_cpp, 2},
    {"_mitodrift_logSumExp", (DL_FUNC) &_mitodrift_logSumExp, 1},
    {"_mitodrift_score_tree_bp", (DL_FUNC) &_mitodrift_score_tree_bp, 7},
    {"_mitodrift_score_tree_bp_wrapper", (DL_FUNC) &_mitodrift_score_tree_bp_wrapper, 3},
    {"_mitodrift_score_tree_bp2", (DL_FUNC) &_mitodrift_score_tree_bp2, 7},
    {"_mitodrift_score_tree_bp_wrapper2", (DL_FUNC) &_mitodrift_score_tree_bp_wrapper2, 3},
    {"_mitodrift_score_trees_parallel", (DL_FUNC) &_mitodrift_score_trees_parallel, 3},
    {"_mitodrift_score_tree_bp_wrapper_multi", (DL_FUNC) &_mitodrift_score_tree_bp_wrapper_multi, 3},
    {"_mitodrift_nni_cpp_parallel", (DL_FUNC) &_mitodrift_nni_cpp_parallel, 3},
    {"_mitodrift_nni_cpp_parallel_cached", (DL_FUNC) &_mitodrift_nni_cpp_parallel_cached, 3},
    {"_mitodrift_nni_cpp_parallel_multi", (DL_FUNC) &_mitodrift_nni_cpp_parallel_multi, 3},
    {"_mitodrift_tree_mcmc_cpp", (DL_FUNC) &_mitodrift_tree_mcmc_cpp, 5},
    {"_mitodrift_tree_mcmc_cpp_cached", (DL_FUNC) &_mitodrift_tree_mcmc_cpp_cached, 5},
    {"_mitodrift_tree_mcmc_cpp_cached_threadsafe", (DL_FUNC) &_mitodrift_tree_mcmc_cpp_cached_threadsafe, 6},
    {"_mitodrift_tree_mcmc_parallel", (DL_FUNC) &_mitodrift_tree_mcmc_parallel, 5},
    {"_mitodrift_tree_mcmc_parallel_seeded", (DL_FUNC) &_mitodrift_tree_mcmc_parallel_seeded, 5},
    {"_mitodrift_save_qd_cpp", (DL_FUNC) &_mitodrift_save_qd_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_mitodrift(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
