// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reorderRcpp
arma::Col<int> reorderRcpp(const arma::Col<int>& E);
RcppExport SEXP _mitodrift_reorderRcpp(SEXP ESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    rcpp_result_gen = Rcpp::wrap(reorderRcpp(E));
    return rcpp_result_gen;
END_RCPP
}
// nnin_cpp
std::vector<arma::Col<int>> nnin_cpp(const arma::Col<int>& E, const int n);
RcppExport SEXP _mitodrift_nnin_cpp(SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nnin_cpp(E, n));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp
double logSumExp(const arma::vec x);
RcppExport SEXP _mitodrift_logSumExp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp(x));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp2
double logSumExp2(const arma::vec& x);
RcppExport SEXP _mitodrift_logSumExp2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp2(x));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp
double score_tree_bp(const arma::Col<int>& E, const std::vector<double>& logP, const std::vector<double>& logA, const int n, const int C, const int m, const int root);
RcppExport SEXP _mitodrift_score_tree_bp(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP nSEXP, SEXP CSEXP, SEXP mSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp(E, logP, logA, n, C, m, root));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_wrapper
double score_tree_bp_wrapper(arma::Col<int> E, const std::vector< std::vector<double> >& logP_list, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_score_tree_bp_wrapper(SEXP ESEXP, SEXP logP_listSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP_list(logP_listSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_wrapper(E, logP_list, logA));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp2
double score_tree_bp2(const arma::Col<int>& E, const std::vector<double>& logP, const std::vector<double>& logA, const int n, const int C, const int m, const int root);
RcppExport SEXP _mitodrift_score_tree_bp2(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP, SEXP nSEXP, SEXP CSEXP, SEXP mSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Col<int>& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp2(E, logP, logA, n, C, m, root));
    return rcpp_result_gen;
END_RCPP
}
// score_tree_bp_wrapper2
double score_tree_bp_wrapper2(arma::Col<int> E, const std::vector< std::vector<double> >& logP_list, const std::vector<double>& logA);
RcppExport SEXP _mitodrift_score_tree_bp_wrapper2(SEXP ESEXP, SEXP logP_listSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector< std::vector<double> >& >::type logP_list(logP_listSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(score_tree_bp_wrapper2(E, logP_list, logA));
    return rcpp_result_gen;
END_RCPP
}
// nni_cpp_parallel
NumericVector nni_cpp_parallel(arma::Col<int> E, const std::vector<std::vector<double>> logP, const std::vector<double> logA);
RcppExport SEXP _mitodrift_nni_cpp_parallel(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>> >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(nni_cpp_parallel(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}
// nni_cpp_parallel2
NumericVector nni_cpp_parallel2(arma::Col<int> E, const std::vector<std::vector<double>> logP, const std::vector<double> logA);
RcppExport SEXP _mitodrift_nni_cpp_parallel2(SEXP ESEXP, SEXP logPSEXP, SEXP logASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type E(ESEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>> >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type logA(logASEXP);
    rcpp_result_gen = Rcpp::wrap(nni_cpp_parallel2(E, logP, logA));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mitodrift_reorderRcpp", (DL_FUNC) &_mitodrift_reorderRcpp, 1},
    {"_mitodrift_nnin_cpp", (DL_FUNC) &_mitodrift_nnin_cpp, 2},
    {"_mitodrift_logSumExp", (DL_FUNC) &_mitodrift_logSumExp, 1},
    {"_mitodrift_logSumExp2", (DL_FUNC) &_mitodrift_logSumExp2, 1},
    {"_mitodrift_score_tree_bp", (DL_FUNC) &_mitodrift_score_tree_bp, 7},
    {"_mitodrift_score_tree_bp_wrapper", (DL_FUNC) &_mitodrift_score_tree_bp_wrapper, 3},
    {"_mitodrift_score_tree_bp2", (DL_FUNC) &_mitodrift_score_tree_bp2, 7},
    {"_mitodrift_score_tree_bp_wrapper2", (DL_FUNC) &_mitodrift_score_tree_bp_wrapper2, 3},
    {"_mitodrift_nni_cpp_parallel", (DL_FUNC) &_mitodrift_nni_cpp_parallel, 3},
    {"_mitodrift_nni_cpp_parallel2", (DL_FUNC) &_mitodrift_nni_cpp_parallel2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mitodrift(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
