# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' definitions for logSumExp function
NULL

allChildrenCPP <- function(E) {
    .Call('_mitodrift_allChildrenCPP', PACKAGE = 'mitodrift', E)
}

reorder_rows <- function(x, y) {
    .Call('_mitodrift_reorder_rows', PACKAGE = 'mitodrift', x, y)
}

reorderRcpp <- function(E) {
    .Call('_mitodrift_reorderRcpp', PACKAGE = 'mitodrift', E)
}

nnin_cpp <- function(E, n) {
    .Call('_mitodrift_nnin_cpp', PACKAGE = 'mitodrift', E, n)
}

node_depth <- function(ntip, e1, e2, nedge, xx, method) {
    .Call('_mitodrift_node_depth', PACKAGE = 'mitodrift', ntip, e1, e2, nedge, xx, method)
}

#' logSumExp function for a vector
#'
#' @param x NumericVector
#' @return double logSumExp of x
#' @export
logSumExp <- function(x) {
    .Call('_mitodrift_logSumExp', PACKAGE = 'mitodrift', x)
}

score_tree_bp <- function(E, logP, logA) {
    .Call('_mitodrift_score_tree_bp', PACKAGE = 'mitodrift', E, logP, logA)
}

score_tree_bp_wrapper <- function(E, logP, logA) {
    .Call('_mitodrift_score_tree_bp_wrapper', PACKAGE = 'mitodrift', E, logP, logA)
}

logSumExpMat <- function(X, axis = 0L) {
    .Call('_mitodrift_logSumExpMat', PACKAGE = 'mitodrift', X, axis)
}

score_tree_bp_multi <- function(E, logP, logA) {
    .Call('_mitodrift_score_tree_bp_multi', PACKAGE = 'mitodrift', E, logP, logA)
}

nni_cpp_parallel <- function(tree, logP, logA) {
    .Call('_mitodrift_nni_cpp_parallel', PACKAGE = 'mitodrift', tree, logP, logA)
}

