# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_leaf_liks_mat_cpp <- function(amat, dmat, vafs, eps = 0.0, ncores = 1L, log = FALSE) {
    .Call('_mitodrift_get_leaf_liks_mat_cpp', PACKAGE = 'mitodrift', amat, dmat, vafs, eps, ncores, log)
}

#' definitions for logSumExp function
NULL

reorderRcpp <- function(E) {
    .Call('_mitodrift_reorderRcpp', PACKAGE = 'mitodrift', E)
}

nnin_cpp <- function(E, n) {
    .Call('_mitodrift_nnin_cpp', PACKAGE = 'mitodrift', E, n)
}

#' logSumExp function for a vector
#'
#' @param x NumericVector
#' @return double logSumExp of x
#' @export
logSumExp <- function(x) {
    .Call('_mitodrift_logSumExp', PACKAGE = 'mitodrift', x)
}

score_tree_bp <- function(E, logP, logA, n, C, m, root) {
    .Call('_mitodrift_score_tree_bp', PACKAGE = 'mitodrift', E, logP, logA, n, C, m, root)
}

score_tree_bp_wrapper <- function(E, logP_list, logA) {
    .Call('_mitodrift_score_tree_bp_wrapper', PACKAGE = 'mitodrift', E, logP_list, logA)
}

score_tree_bp2 <- function(E, logP, logA, n, C, m, root) {
    .Call('_mitodrift_score_tree_bp2', PACKAGE = 'mitodrift', E, logP, logA, n, C, m, root)
}

score_tree_bp_wrapper2 <- function(E, logP_list, logA) {
    .Call('_mitodrift_score_tree_bp_wrapper2', PACKAGE = 'mitodrift', E, logP_list, logA)
}

score_trees_parallel <- function(trees, logP, logA) {
    .Call('_mitodrift_score_trees_parallel', PACKAGE = 'mitodrift', trees, logP, logA)
}

score_tree_bp_wrapper_multi <- function(E, logP_list, logA_list) {
    .Call('_mitodrift_score_tree_bp_wrapper_multi', PACKAGE = 'mitodrift', E, logP_list, logA_list)
}

nni_cpp_parallel <- function(E, logP, logA) {
    .Call('_mitodrift_nni_cpp_parallel', PACKAGE = 'mitodrift', E, logP, logA)
}

nni_cpp_parallel_cached <- function(E, logP, logA) {
    .Call('_mitodrift_nni_cpp_parallel_cached', PACKAGE = 'mitodrift', E, logP, logA)
}

nni_cpp_parallel_multi <- function(E, logP, logA) {
    .Call('_mitodrift_nni_cpp_parallel_multi', PACKAGE = 'mitodrift', E, logP, logA)
}

tree_mcmc_cpp <- function(E, logP, logA, max_iter = 100L, seed = -1L) {
    .Call('_mitodrift_tree_mcmc_cpp', PACKAGE = 'mitodrift', E, logP, logA, max_iter, seed)
}

tree_mcmc_cpp_cached <- function(E, logP, logA, max_iter = 100L, seed = -1L) {
    .Call('_mitodrift_tree_mcmc_cpp_cached', PACKAGE = 'mitodrift', E, logP, logA, max_iter, seed)
}

tree_mcmc_parallel <- function(E, logP, logA, max_iter, nchains) {
    .Call('_mitodrift_tree_mcmc_parallel', PACKAGE = 'mitodrift', E, logP, logA, max_iter, nchains)
}

