# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' definitions for logSumExp function
NULL

reorderRcpp <- function(E) {
    .Call('_mitodrift_reorderRcpp', PACKAGE = 'mitodrift', E)
}

nnin_cpp <- function(E, n) {
    .Call('_mitodrift_nnin_cpp', PACKAGE = 'mitodrift', E, n)
}

nnin_cpp2 <- function(E, n) {
    .Call('_mitodrift_nnin_cpp2', PACKAGE = 'mitodrift', E, n)
}

node_depth <- function(ntip, e1, e2, nedge, xx, method) {
    .Call('_mitodrift_node_depth', PACKAGE = 'mitodrift', ntip, e1, e2, nedge, xx, method)
}

#' logSumExp function for a vector
#'
#' @param x NumericVector
#' @return double logSumExp of x
#' @export
logSumExp <- function(x) {
    .Call('_mitodrift_logSumExp', PACKAGE = 'mitodrift', x)
}

score_tree_bp <- function(E, logP, logA, n, C, m, root) {
    .Call('_mitodrift_score_tree_bp', PACKAGE = 'mitodrift', E, logP, logA, n, C, m, root)
}

score_tree_bp_wrapper <- function(E, logP_list, logA) {
    .Call('_mitodrift_score_tree_bp_wrapper', PACKAGE = 'mitodrift', E, logP_list, logA)
}

nni_cpp_parallel <- function(E, logP, logA) {
    .Call('_mitodrift_nni_cpp_parallel', PACKAGE = 'mitodrift', E, logP, logA)
}

